/* 
 * Author: Lim Rui An Ryan
 * Filename: ToolUIQuickAccess.cs
 * Description: A script that is to be attached to the interface element generated by the ToolUIGenerator to allow for quick access to the variables required in game logic
 */
using UnityEngine.UI;
using UnityEngine;
using TMPro;

public class ToolUIQuickAccess : MonoBehaviour {
    // Public
    public Image IconSelf;
    public GameObject LockedIcon;
    public GameObject SelectedIcon;
    public TextMeshProUGUI ToolTip;
    public ARCleanDataStore.PlayerTool ToolType = ARCleanDataStore.PlayerTool.PT_Undefined;

    // Private
    [SerializeField] Sprite Icon_Sponge;
    [SerializeField] Sprite Icon_Genie;
    [SerializeField] Sprite Icon_Kellen;
    [SerializeField] Sprite Icon_DryCloth;
    [SerializeField] Sprite Icon_CookingOil;
    [SerializeField] Sprite Icon_Alcosan;
    [SerializeField] Sprite Icon_Broom;
    [SerializeField] Sprite Icon_Glove;
    [SerializeField] Sprite Icon_Water;
    [SerializeField] Sprite Icon_Alkaclean;
    [SerializeField] Sprite Icon_Wiper;
    [SerializeField] Sprite Icon_HardBrush;
    private bool Locked = true;

    public void SetPlayerTool()
    {
        if (!LockedIcon.activeSelf)
        {
            if (ARCleanDataStore.GetPlayerTool() != ARCleanDataStore.PlayerTool.PT_Undefined && ARCleanDataStore.GetPlayerTool() == ToolType)
            {
                ARCleanDataStore.SetPlayerTool(ARCleanDataStore.PlayerTool.PT_Undefined);
                return;
            }
            ARCleanDataStore.SetPlayerTool(ToolType);
            SetToolIconBasedOnType();
            Locked = false;

            //if (ARCleanDataStore.ModelAccess.ScrollerModule)
            //    ARCleanDataStore.ModelAccess.ScrollerModule.LerpToPage((int)ToolType - 1);
        }
    }

    public void SetButtonInteractability(bool Interactable)
    {
        IconSelf.gameObject.GetComponent<Button>().interactable = Interactable;
    }

    public bool GetLocked()
    {
        return Locked;
    }

    public void SetIconBasedOnType()
    {
        switch (ToolType)
        {
            case ARCleanDataStore.PlayerTool.PT_Sponge:
                if (Icon_Sponge != null)
                    IconSelf.sprite = Icon_Sponge;
                ToolTip.text = "Sponge";
                break;
            case ARCleanDataStore.PlayerTool.PT_HeavySpongeGenie:
                if (Icon_Genie != null)
                    IconSelf.sprite = Icon_Genie;
                ToolTip.text = "Genie";
                break;
            case ARCleanDataStore.PlayerTool.PT_HeavySpongeKellen:
                if (Icon_Kellen != null)
                    IconSelf.sprite = Icon_Kellen;
                ToolTip.text = "Kleen";
                break;
            case ARCleanDataStore.PlayerTool.PT_DryCloth:
                if (Icon_DryCloth != null)
                    IconSelf.sprite = Icon_DryCloth;
                ToolTip.text = "Dry Cloth";
                break;
            case ARCleanDataStore.PlayerTool.PT_CookingOil:
                if (Icon_CookingOil != null)
                    IconSelf.sprite = Icon_CookingOil;
                ToolTip.text = "Cooking Oil";
                break;
            case ARCleanDataStore.PlayerTool.PT_Alcosan:
                if (Icon_Alcosan != null)
                    IconSelf.sprite = Icon_Alcosan;
                ToolTip.text = "Alcosan";
                break;
            case ARCleanDataStore.PlayerTool.PT_Broom:
                if (Icon_DryCloth != null)
                    IconSelf.sprite = Icon_Broom;
                ToolTip.text = "Broom";
                break;
            case ARCleanDataStore.PlayerTool.PT_Glove:
                if (Icon_CookingOil != null)
                    IconSelf.sprite = Icon_Glove;
                ToolTip.text = "Metal Glove";
                break;
            case ARCleanDataStore.PlayerTool.PT_Water:
                if (Icon_Water != null)
                    IconSelf.sprite = Icon_Water;
                ToolTip.text = "Pail of Water";
                break;
            case ARCleanDataStore.PlayerTool.PT_Alkaclean:
                if (Icon_Alkaclean != null)
                    IconSelf.sprite = Icon_Alkaclean;
                ToolTip.text = "Alkaclean";
                break;
            case ARCleanDataStore.PlayerTool.PT_Wiper:
                if (Icon_Wiper != null)
                    IconSelf.sprite = Icon_Wiper;
                ToolTip.text = "Wiper";
                break;
            case ARCleanDataStore.PlayerTool.PT_HardBrush:
                if (Icon_HardBrush != null)
                    IconSelf.sprite = Icon_HardBrush;
                ToolTip.text = "Hard Brush";
                break;
        }
    }

    public void SetToolIconBasedOnType()
    {
        if (ARCleanDataStore.ModelAccess.CurrentToolImage == null)
            return;
        switch (ToolType)
        {
            case ARCleanDataStore.PlayerTool.PT_Sponge:
                if (Icon_Sponge != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Sponge;
                break;
            case ARCleanDataStore.PlayerTool.PT_HeavySpongeGenie:
                if (Icon_Genie != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Genie;
                break;
            case ARCleanDataStore.PlayerTool.PT_HeavySpongeKellen:
                if (Icon_Kellen != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Kellen;
                break;
            case ARCleanDataStore.PlayerTool.PT_DryCloth:
                if (Icon_DryCloth != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_DryCloth;
                break;
            case ARCleanDataStore.PlayerTool.PT_CookingOil:
                if (Icon_CookingOil != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_CookingOil;
                break;
            case ARCleanDataStore.PlayerTool.PT_Alcosan:
                if (Icon_Alcosan != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Alcosan;
                break;
            case ARCleanDataStore.PlayerTool.PT_Broom:
                if (Icon_DryCloth != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Broom;
                break;
            case ARCleanDataStore.PlayerTool.PT_Glove:
                if (Icon_CookingOil != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Glove;
                break;
            case ARCleanDataStore.PlayerTool.PT_Water:
                if (Icon_Water != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Water;
                break;
            case ARCleanDataStore.PlayerTool.PT_Alkaclean:
                if (Icon_Alkaclean != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Alkaclean;
                break;
            case ARCleanDataStore.PlayerTool.PT_Wiper:
                if (Icon_Wiper != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_Wiper;
                break;
            case ARCleanDataStore.PlayerTool.PT_HardBrush:
                if (Icon_HardBrush != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = Icon_HardBrush;
                break;
            default:
                if (ARCleanDataStore.ModelAccess.DefaultToolIcon != null)
                    ARCleanDataStore.ModelAccess.CurrentToolImage.sprite = ARCleanDataStore.ModelAccess.DefaultToolIcon;
                break;
        }
    }
}